/*
* This file is part of the Head Tracker distribution (https://github.com/dlktdr/headtracker)
* Copyright (c) 2022 Cliff Blackburn
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, version 3.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/**********************************************
 *
 *  !!! THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT DIRECTLY !!!
 *
 *  Modify /utils/settings.csv and execute buildsettings.py to generate this bluetooth header
 *
 ***********************************************/

/* This file contains the settings which are be adjustable via Bluetooth Web App
 */

#pragma once

#include <zephyr.h>

#include <bluetooth/bluetooth.h>
#include <bluetooth/conn.h>
#include <bluetooth/gatt.h>
#include <bluetooth/hci.h>
#include <bluetooth/uuid.h>

extern uint16_t bt_rll_min;
extern uint16_t bt_rll_max;
extern uint16_t bt_rll_cnt;
extern float bt_rll_gain;
extern uint16_t bt_tlt_min;
extern uint16_t bt_tlt_max;
extern uint16_t bt_tlt_cnt;
extern float bt_tlt_gain;
extern uint16_t bt_pan_min;
extern uint16_t bt_pan_max;
extern uint16_t bt_pan_cnt;
extern float bt_pan_gain;
extern int8_t bt_tltch;
extern int8_t bt_rllch;
extern int8_t bt_panch;
extern int8_t bt_alertch;
extern int8_t bt_pwm0;
extern int8_t bt_pwm1;
extern int8_t bt_pwm2;
extern int8_t bt_pwm3;
extern int8_t bt_an0ch;
extern int8_t bt_an1ch;
extern int8_t bt_an2ch;
extern int8_t bt_an3ch;
extern int8_t bt_aux0ch;
extern int8_t bt_aux1ch;
extern int8_t bt_aux2ch;
extern float bt_an0gain;
extern float bt_an1gain;
extern float bt_an2gain;
extern float bt_an3gain;
extern float bt_an0off;
extern float bt_an1off;
extern float bt_an2off;
extern float bt_an3off;
extern bool bt_dismag;

extern struct bt_uuid_16 bt_uuid_rll_min;
extern struct bt_uuid_16 bt_uuid_rll_max;
extern struct bt_uuid_16 bt_uuid_rll_cnt;
extern struct bt_uuid_16 bt_uuid_rll_gain;
extern struct bt_uuid_16 bt_uuid_tlt_min;
extern struct bt_uuid_16 bt_uuid_tlt_max;
extern struct bt_uuid_16 bt_uuid_tlt_cnt;
extern struct bt_uuid_16 bt_uuid_tlt_gain;
extern struct bt_uuid_16 bt_uuid_pan_min;
extern struct bt_uuid_16 bt_uuid_pan_max;
extern struct bt_uuid_16 bt_uuid_pan_cnt;
extern struct bt_uuid_16 bt_uuid_pan_gain;
extern struct bt_uuid_16 bt_uuid_tltch;
extern struct bt_uuid_16 bt_uuid_rllch;
extern struct bt_uuid_16 bt_uuid_panch;
extern struct bt_uuid_16 bt_uuid_alertch;
extern struct bt_uuid_16 bt_uuid_pwm0;
extern struct bt_uuid_16 bt_uuid_pwm1;
extern struct bt_uuid_16 bt_uuid_pwm2;
extern struct bt_uuid_16 bt_uuid_pwm3;
extern struct bt_uuid_16 bt_uuid_an0ch;
extern struct bt_uuid_16 bt_uuid_an1ch;
extern struct bt_uuid_16 bt_uuid_an2ch;
extern struct bt_uuid_16 bt_uuid_an3ch;
extern struct bt_uuid_16 bt_uuid_aux0ch;
extern struct bt_uuid_16 bt_uuid_aux1ch;
extern struct bt_uuid_16 bt_uuid_aux2ch;
extern struct bt_uuid_16 bt_uuid_an0gain;
extern struct bt_uuid_16 bt_uuid_an1gain;
extern struct bt_uuid_16 bt_uuid_an2gain;
extern struct bt_uuid_16 bt_uuid_an3gain;
extern struct bt_uuid_16 bt_uuid_an0off;
extern struct bt_uuid_16 bt_uuid_an1off;
extern struct bt_uuid_16 bt_uuid_an2off;
extern struct bt_uuid_16 bt_uuid_an3off;
extern struct bt_uuid_16 bt_uuid_dismag;

ssize_t btwr_rll_min(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_rll_min(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_rll_max(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_rll_max(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_rll_cnt(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_rll_cnt(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_rll_gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_rll_gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_tlt_min(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_tlt_min(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_tlt_max(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_tlt_max(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_tlt_cnt(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_tlt_cnt(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_tlt_gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_tlt_gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_pan_min(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_pan_min(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_pan_max(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_pan_max(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_pan_cnt(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_pan_cnt(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_pan_gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_pan_gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_tltch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_tltch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_rllch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_rllch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_panch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_panch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_alertch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_alertch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_pwm0(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_pwm0(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_pwm1(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_pwm1(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_pwm2(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_pwm2(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_pwm3(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_pwm3(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an0ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an0ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an1ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an1ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an2ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an2ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an3ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an3ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_aux0ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_aux0ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_aux1ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_aux1ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_aux2ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_aux2ch(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an0gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an0gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an1gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an1gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an2gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an2gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an3gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an3gain(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an0off(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an0off(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an1off(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an1off(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an2off(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an2off(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_an3off(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_an3off(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);
ssize_t btwr_dismag(struct bt_conn *conn, const struct bt_gatt_attr *attr, const void *buf, uint16_t len, uint16_t offset, uint8_t flags);
ssize_t btrd_dismag(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf, uint16_t len, uint16_t offset);

#define AUTOGENERATED_CHARACTERISTICS \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_rll_min.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_rll_min, btwr_rll_min, (void*)&bt_rll_min) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_rll_max.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_rll_max, btwr_rll_max, (void*)&bt_rll_max) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_rll_cnt.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_rll_cnt, btwr_rll_cnt, (void*)&bt_rll_cnt) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_rll_gain.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_rll_gain, btwr_rll_gain, (void*)&bt_rll_gain) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_tlt_min.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_tlt_min, btwr_tlt_min, (void*)&bt_tlt_min) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_tlt_max.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_tlt_max, btwr_tlt_max, (void*)&bt_tlt_max) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_tlt_cnt.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_tlt_cnt, btwr_tlt_cnt, (void*)&bt_tlt_cnt) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_tlt_gain.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_tlt_gain, btwr_tlt_gain, (void*)&bt_tlt_gain) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_pan_min.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_pan_min, btwr_pan_min, (void*)&bt_pan_min) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_pan_max.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_pan_max, btwr_pan_max, (void*)&bt_pan_max) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_pan_cnt.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_pan_cnt, btwr_pan_cnt, (void*)&bt_pan_cnt) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_pan_gain.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_pan_gain, btwr_pan_gain, (void*)&bt_pan_gain) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_tltch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_tltch, btwr_tltch, (void*)&bt_tltch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_rllch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_rllch, btwr_rllch, (void*)&bt_rllch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_panch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_panch, btwr_panch, (void*)&bt_panch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_alertch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_alertch, btwr_alertch, (void*)&bt_alertch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_pwm0.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_pwm0, btwr_pwm0, (void*)&bt_pwm0) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_pwm1.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_pwm1, btwr_pwm1, (void*)&bt_pwm1) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_pwm2.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_pwm2, btwr_pwm2, (void*)&bt_pwm2) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_pwm3.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_pwm3, btwr_pwm3, (void*)&bt_pwm3) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an0ch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an0ch, btwr_an0ch, (void*)&bt_an0ch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an1ch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an1ch, btwr_an1ch, (void*)&bt_an1ch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an2ch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an2ch, btwr_an2ch, (void*)&bt_an2ch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an3ch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an3ch, btwr_an3ch, (void*)&bt_an3ch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_aux0ch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_aux0ch, btwr_aux0ch, (void*)&bt_aux0ch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_aux1ch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_aux1ch, btwr_aux1ch, (void*)&bt_aux1ch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_aux2ch.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_aux2ch, btwr_aux2ch, (void*)&bt_aux2ch) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an0gain.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an0gain, btwr_an0gain, (void*)&bt_an0gain) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an1gain.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an1gain, btwr_an1gain, (void*)&bt_an1gain) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an2gain.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an2gain, btwr_an2gain, (void*)&bt_an2gain) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an3gain.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an3gain, btwr_an3gain, (void*)&bt_an3gain) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an0off.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an0off, btwr_an0off, (void*)&bt_an0off) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an1off.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an1off, btwr_an1off, (void*)&bt_an1off) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an2off.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an2off, btwr_an2off, (void*)&bt_an2off) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_an3off.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_an3off, btwr_an3off, (void*)&bt_an3off) \
    ,BT_GATT_CHARACTERISTIC(&bt_uuid_dismag.uuid, BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE, \
                                                   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, \
                                                   btrd_dismag, btwr_dismag, (void*)&bt_dismag) \

